In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Edunet Foundation\Desktop\Students_handover\Categorical_encoding\cars (1).csv')

In [3]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [4]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [5]:
df['brand'].value_counts().nunique()

27

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# 1. OneHotEncoding using Pandas

In [8]:
pd.get_dummies(df, columns=['owner', 'fuel'])

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,True,False,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,False,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,True,False,False
4,Maruti,120000,130000,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,True,False,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,False,True,False,False,False,False,True,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,True,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,True,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,True,False,False

# 2. K-1 OneHotEncoding

In [9]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3. OneHotEncoding using Sklearn

#### when we do one hot encoding using pandas it will not be good because it does not remeber the order of the columns and
####  it will create new columns if we have new categories in the test data which were not present in the training data. 
#### So we will use sklearn for one hot encoding.

In [12]:
x = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [13]:
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe = OneHotEncoder()

In [ ]:
ohe.fit_transform(df[['owner', 'fuel']])
# it will give us a sparse matrix, we can convert it to an array using toarray() method

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16256 stored elements and shape (8128, 9)>

In [18]:
ohe.fit_transform(df[['owner', 'fuel']]).toarray()

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]], shape=(8128, 9))

In [ ]:
# Sparse matrix is a matrix that contains a lot of zeros, it is used to save memory and computational time when we have a 
# large dataset with a lot of categorical variables.